//

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAoPH_uHqA_UcWpz06FOHE4pPzCkb8TkzI",
      authDomain: "workout-planner88.firebaseapp.com",
      projectId: "workout-planner88",
      storageBucket: "workout-planner88.appspot.com",
      messagingSenderId: "997508079138",
      appId: "1:997508079138:web:d08b9805043f1b815c747b",
      measurementId: "G-B990GL27YZ"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAoPH_uHqA_UcWpz06FOHE4pPzCkb8TkzI",
      authDomain: "workout-planner88.firebaseapp.com",
      projectId: "workout-planner88",
      storageBucket: "workout-planner88.appspot.com",
      messagingSenderId: "997508079138",
      appId: "1:997508079138:web:d08b9805043f1b815c747b",
      measurementId: "G-B990GL27YZ"
  );

  static const FirebaseOptions ios = FirebaseOptions(
      apiKey: "AIzaSyAoPH_uHqA_UcWpz06FOHE4pPzCkb8TkzI",
      authDomain: "workout-planner88.firebaseapp.com",
      projectId: "workout-planner88",
      storageBucket: "workout-planner88.appspot.com",
      messagingSenderId: "997508079138",
      appId: "1:997508079138:web:d08b9805043f1b815c747b",
      measurementId: "G-B990GL27YZ"
  );

  static const FirebaseOptions macos = FirebaseOptions(
      apiKey: "AIzaSyAoPH_uHqA_UcWpz06FOHE4pPzCkb8TkzI",
      authDomain: "workout-planner88.firebaseapp.com",
      projectId: "workout-planner88",
      storageBucket: "workout-planner88.appspot.com",
      messagingSenderId: "997508079138",
      appId: "1:997508079138:web:d08b9805043f1b815c747b",
      measurementId: "G-B990GL27YZ"
  );
}
